### PR TITLE
fixing neogeo issues.

### PR DESCRIPTION
**Pull request by ElRojo**

### CODE REVIEW

**Comment by ElRojo** [comment]
@coded-with-claws 

can you load this rfid_write file and see if this fixes your issues with NeoGeo? I implemented a couple of your fixes from the other branch, but also added those goofy case statements that slipped through. I noticed that the NeoGeo array wasn't being properly searched and that the `findIt` function was running twice, overwriting previously written variables. 

Additionally, the list of games isn't perfect. Some of my games on my MiSTer aren't found in this list. I added an exit there so that the script halts if the games aren't found. We can fix these later.

I tested this both running a local games folder as well as a games folder on a USB with positive results. Let me know how it goes for you.

**Comment by coded-with-claws** [comment]
Wow, it works great and I no longer have to move the mgl file to fat!!
I wonder how this was fixed, I only see a difference into the delay value, but I'm happy!

I can see you kept my changes :+1: 
Nice addition for the err.mp3!!
I increased its volume in a commit.
I also added a small fix for the serial_listen (although it's OK in your update script, I think it's better to fix the new path for people who would manually install).

I think you're good to go with this branch! :+1:

**Comment by ElRojo** [comment]
> Wow, it works great and I no longer have to move the mgl file to fat!! I wonder how this was fixed, I only see a difference into the delay value, but I'm happy!
> 
> I can see you kept my changes 👍 Nice addition for the err.mp3!! I increased its volume in a commit. I also added a small fix for the serial_listen (although it's OK in your update script, I think it's better to fix the new path for people who would manually install).
> 
> I think you're good to go with this branch! 👍

Thanks so much :) 

I'm glad to hear this seems to work! I believe the biggest issue was that `findIt` was being called twice and overwriting variables that were already set. 

Thanks again for all your help!

**Comment by ElRojo** [comment]
Just a heads up @coded-with-claws, since this file is being sourced, the `exit 1` in `neGeoFileFixer` command closes the screen session. I removed that exit so that the serial_listen doesn't close. That change has been pushed to main.

**Comment by coded-with-claws** [comment]
Thanks for the info, I hadn't seen :)

**Pull request merged**
