### PR TITLE
play sounds when reading tags (write card, write conf, run game)

### PR DESCRIPTION
**Pull request by coded-with-claws**
Hi!
I thought the write tag featured lacked a little of feedback, because I could only see the red LED when conf file is written.
I wasn't always sure whether the write card was read, and I plan to hide my RFID reader in my MiSTer box.
So I propose that we play sounds when tags are read :)
- write card is read (there was no easy sign to know it except for the Arduino LEDs)
- rfid_write.sh is called (we could see it with the RED LED of the MiSTer because it writes on SD card)
- rfid_process.sh is called (this sound is not really useful, it's for fun!)

Also, you can note that know into the .ino file, we can setup the ID of the write card at the beginning of the file with a #define, it's more convenient than scrolling into the code.

I hope you'll like this addition.
I didn't find problems when testing, but your tests will be welcome!
I'll be there if you need info!

### CODE REVIEW

**Comment by coded-with-claws** [comment]
One more info: for the "run game sound", depending on the core already loaded, the beginning of the sound may not really be audible. I guess it's related to the audio management of the core.
For example, if the SNES core is already loaded, the sound will run fine, but for some Arcade core, we only hear the end of the sound.
I don't think I can fix this issue...

**Comment by ElRojo** [comment]
> One more info: for the "run game sound", depending on the core already loaded, the beginning of the sound may not really be audible. I guess it's related to the audio management of the core.
> For example, if the SNES core is already loaded, the sound will run fine, but for some Arcade core, we only hear the end of the sound.
> I don't think I can fix this issue...

Love these changes. I’m not at a computer right now so I’ll review and test later today.

I’m also working on an installer script that will make installing / updating easier.

**Review by ElRojo — APPROVED** [review]
Tested these changes and they work well. Great catch for the constant in the ino file, too. I'm not much of a C writer so I'm glad you were able to make that easier for everyone. 

Great choices for sounds, too 👍

**Comment by ElRojo** [comment]
@coded-with-claws I'm going to go ahead and merge this for ya. I have another PR that depends on it :)

**Comment by coded-with-claws** [comment]
Awesome! Thanks a lot!! I didn't expect it to be so quick :+1: 
I see your new branch for the updater, that's great, I'll look at it :)

**Pull request merged**
