### PR TITLE
Utilizing configuration file

### PR DESCRIPTION
**Pull request by ElRojo**

### CODE REVIEW

**Comment by coded-with-claws** [comment]
@ElRojo would you mind adding me the rights to push updates ? There are some fixes in readme that I spotted :)
I received my arduino + rfid reader and I'm trying to make it work, so I'm reading the readme attentively!

**Comment by ElRojo** [comment]
> @ElRojo would you mind adding me the rights to push updates ? There are some fixes in readme that I spotted :)
> I received my arduino + rfid reader and I'm trying to make it work, so I'm reading the readme attentively!

Added, go ahead and give it a shot!

**Comment by coded-with-claws** [comment]
Thanks, I could push the little fixes into readme into this branch :)

**Comment by ElRojo** [comment]
> Thanks, I could push the little fixes into readme into this branch :)

I see them! Thanks for the corrections :) I may merge this branch into main next week. Let me know how your testing goes!

**Comment by coded-with-claws** [comment]
With the code from your conf-file branch, it works great on my MiSTer!
For the non-arcade games, I manually added the qload_rom function into rfid_process.sh (from the snesRFID initial repo) and could run metal slug! I didn't manage to run a SNES game, I suppose it's because it's related to the hierarchy of my SNES games directory (I don't understand yet how the mgl files work).
I see you're working on the neogeo support: is there a reason you want to do it differently than the "qload_rom" original function?

**Comment by coded-with-claws** [comment]
I forgot to say that I couldn't not yet test the "write tag" feature. My arduino is already flashed with javiwwweb's version, I prepared your version of the .ino file with my tag ID, but I didn't manage to compile in Arduino IDE yet (seems broken on Ubuntu, it doesn't find SPI.h...). I hope I'll be able to progress on that.
So I wrote the conf file myself in the meantime.

**Comment by ElRojo** [comment]
> With the code from your conf-file branch, it works great on my MiSTer!
> For the non-arcade games, I manually added the qload_rom function into rfid_process.sh (from the snesRFID initial repo) and could run metal slug! I didn't manage to run a SNES game, I suppose it's because it's related to the hierarchy of my SNES games directory (I don't understand yet how the mgl files work).

Could you show me a screenshot or write out how your SNES files are stored? I would love to solve for this :) 

> I see you're working on the neogeo support: is there a reason you want to do it differently than the "qload_rom" original function?

The `qload_rom` function is actually very similar to what I have in the `writeMgl` fn in rfid_write.sh. I did debate whether to put a processing function similar to `qload_rom`into the rifd_process.sh file. In the end I decided that I'd prefer to have logic run during "write" or "game addition" time, instead of having it run at a time that I could minimize run-time slightly and just run an `echo` with the command necessary. I could throw another function into rfid_process.sh; but ¯\_(ツ)_/¯. Maybe another time, lol. 


`mgl` files seem tricky at first, but they're actually quite simple. The main reason for using them is that `load_core`, as you may already know, only loads a core. You can't echo a file like `Crash Bandicoot.cue` into it as the PSX core won't get loaded and the MiSTer will hang and require a restart (at least in my experience). The `mgl` files are a small instruction set on where to find the core for a game and the path to the game. It also includes the mount type and index values which you can read about here: https://mister-devel.github.io/MkDocs_MiSTer/advanced/mgl/.

`mra` files act as a map (very similar to `mgl`) so that's why they can be echo'd the say way an `mgl` can. 


> I forgot to say that I couldn't not yet test the "write tag" feature. My arduino is already flashed with javiwwweb's version, I prepared your version of the .ino file with my tag ID, but I didn't manage to compile in Arduino IDE yet (seems broken on Ubuntu, it doesn't find SPI.h...). I hope I'll be able to progress on that.
So I wrote the conf file myself in the meantime.

Make sure you install the "Easy MFRC522" library on your Arduino IDE by Pablo Sampaio. That will download some dependencies. I may have omitted that from the ReadMe. I'll go check in a bit and add it in if needed. Maybe I'll even do a little YouTube video on how to get this all set up.

I think you'll find the "write" feature really helpful when you have a large stack of cards! The main purpose for this fork was that I will have a large selection of RFID cards that family-members and friends can choose from instead of having to teach them how to navigate the OSD :). Also, since I plan to have many cards, I didn't want to have to manually add each one by copy/pasting a bunch of files! lol.

**Comment by coded-with-claws** [comment]
Thanks for providing me all this information and your help!

## SNES
Here is my hierarchy : 
```
ls -l /media/usb0/games/SNES/00-fav/puzzle/
total 489856
-rwxr-xr-x 1 root root    347051 Apr  3  2021 'Goof Troop (F).zip'
-rwxr-xr-x 1 root root    346952 Apr  4  2021 'Goof Troop (U) [!].zip'
-rwxr-xr-x 1 root root   1075029 Feb 28  2021 'Lemmings 2 - The Tribes (E).zip'
[...]
```
I also have other folders instead of `puzzle`: `beat_em_up`, `action_platform`, etc.

I also have a "Favorites" directory thanks to the "Favorites" script for MiSTer (https://github.com/wizzomafizzo/MiSTer_Favorites) : 
```
ls -l /media/fat/_\@Favorites/
total 96
lrwxr-xr-x 1 root root  24 Sep  3 17:40  cores -> /media/fat/_Arcade/cores
-rwxr-xr-x 1 root root 264 Sep  3 17:41 'Donkey Kong Country (USA) (Rev 2) (MSU1).mgl'
-rwxr-xr-x 1 root root 205 Sep  3 17:52 'Super Bomberman 2 (U) [!].mgl'
```

All my games are into `usb0`, not `fat`.
So I have edited the `rfid_write.sh` file to have:
```
rootPath=/media/usb0/
```

## qload_rom
Oh ok, the logic is now inside the  `rfid_write.sh` script. I hadn't seen that! Seems great for me, no need to do it anymore in the  `rfid_process.sh` script then.

## Arduino
It's fixed now. I was trying to use Arduino IDE from Ubuntu packages, which seems broken. I now have installed Arduino IDE from the tarball from the official site, and installed the lib "Easy MFRC522", everything is now recognized! It can be noted that, before, I had the lib "MFRC522" (not the "Easy") and it gave compile errors.
So now the arduino can launch the rfid_write.sh when I scan my "write tag"! But it gives errors (see next chapter).
I understand the need to use the "write" function when we have lots of card! I bought 20 tags so I think I'll be happy to easily associate them with the games thanks to the "write tag" feature!

## Current problem
When I run "The punisher" (CPS1), then I scan my "write tag" then my tag 1589700154, I see in the "screen" process some errors, and the tag doesn't run the game (after I launched another game of course):
```
bash: rfid_util/rfid_neoGeo_games.sh: No such file or directory
cat: /tmp/STARTPATH: No such file or directory
cat: /tmp/FULLPATH: No such file or directory
cat: /tmp/CURRENTPATH: No such file or directory
cat: /tmp/CURRENTPATH: No such file or directory
cat: /tmp/STARTPATH: No such file or directory
isDirRtn is equal to 0 before statement
```
Did you already encountered these errors?
For the sourcing of rfid_neoGeo_games.sh, I guess it could be fixed with the absolute path, but I don't understand the other errors.

The config file was updated but with broken info:
```
#################################################################################################
#Game List                                                                                      #
#################################################################################################
1589700154	echo load_core "/media/usb0///.mgl" > /dev/MiSTer_cmd
2693700234	echo load_core /media/fat/_Arcade/'Robocop (World revision 4).mra' > /dev/MiSTer_cmd
#################################################################################################
```
Note: I had manually added the Robocop line yesterday.
Also, I tried to revert my change of rootPath to the original value (using "fat"): same problem, with a path containing "fat" instead of usb0 in the conf file.

**Comment by ElRojo** [comment]
No, thank you! You've been a great help! I'll leave some notes in here:

> Thanks for providing me all this information and your help!
> 
> ## SNES
> Here is my hierarchy :
> 
> ```
> ls -l /media/usb0/games/SNES/00-fav/puzzle/
> total 489856
> -rwxr-xr-x 1 root root    347051 Apr  3  2021 'Goof Troop (F).zip'
> -rwxr-xr-x 1 root root    346952 Apr  4  2021 'Goof Troop (U) [!].zip'
> -rwxr-xr-x 1 root root   1075029 Feb 28  2021 'Lemmings 2 - The Tribes (E).zip'
> [...]
> ```
> 
> I also have other folders instead of `puzzle`: `beat_em_up`, `action_platform`, etc.
> 
> I also have a "Favorites" directory thanks to the "Favorites" script for MiSTer (https://github.com/wizzomafizzo/MiSTer_Favorites) :
> 
> ```
> ls -l /media/fat/_\@Favorites/
> total 96
> lrwxr-xr-x 1 root root  24 Sep  3 17:40  cores -> /media/fat/_Arcade/cores
> -rwxr-xr-x 1 root root 264 Sep  3 17:41 'Donkey Kong Country (USA) (Rev 2) (MSU1).mgl'
> -rwxr-xr-x 1 root root 205 Sep  3 17:52 'Super Bomberman 2 (U) [!].mgl'
> ```
> 
> All my games are into `usb0`, not `fat`. So I have edited the `rfid_write.sh` file to have:
> 
> ```
> rootPath=/media/usb0/
> ```
> 

So I think there are three things to solve for here. 

1. the MGL files won't be able to interact with the write card. But this could be a good feature to add later. I imagine it would just grab the path to the MGL file and put it into the conf file. I'll add that to my list of to-do. 
2. For games that are nested more than two directories deep, this branch will fail. I have set up a new `rfid_write.sh` file that _might_ fix it for you. https://github.com/ElRojo/MiSTerRFID/blob/find-file/fat/media/Scripts/rfid_write.sh. Try that one out after updating and let me know! 
3. The current structure only works for games located on the microSD card. That said, this is something I will be revisiting because I have a NAS where most of my ROMs stored so I'll work on that soon.Good idea adding the `rootPath` though. Hopefully I can fix this easily!

> ## qload_rom
> Oh ok, the logic is now inside the `rfid_write.sh` script. I hadn't seen that! Seems great for me, no need to do it anymore in the `rfid_process.sh` script then.
> 
> ## Arduino
> It's fixed now. I was trying to use Arduino IDE from Ubuntu packages, which seems broken. I now have installed Arduino IDE from the tarball from the official site, and installed the lib "Easy MFRC522", everything is now recognized! It can be noted that, before, I had the lib "MFRC522" (not the "Easy") and it gave compile errors. So now the arduino can launch the rfid_write.sh when I scan my "write tag"! But it gives errors (see next chapter). I understand the need to use the "write" function when we have lots of card! I bought 20 tags so I think I'll be happy to easily associate them with the games thanks to the "write tag" feature!
> 
> ## Current problem
> When I run "The punisher" (CPS1), then I scan my "write tag" then my tag 1589700154, I see in the "screen" process some errors, and the tag doesn't run the game (after I launched another game of course):
> 
> ```
> bash: rfid_util/rfid_neoGeo_games.sh: No such file or directory
> cat: /tmp/STARTPATH: No such file or directory
> cat: /tmp/FULLPATH: No such file or directory
> cat: /tmp/CURRENTPATH: No such file or directory
> cat: /tmp/CURRENTPATH: No such file or directory
> cat: /tmp/STARTPATH: No such file or directory
> isDirRtn is equal to 0 before statement
> ```
> 
> Did you already encountered these errors? For the sourcing of rfid_neoGeo_games.sh, I guess it could be fixed with the absolute path, but I don't understand the other errors.
> 
> The config file was updated but with broken info:
> 
> ```
> #################################################################################################
> #Game List                                                                                      #
> #################################################################################################
> 1589700154	echo load_core "/media/usb0///.mgl" > /dev/MiSTer_cmd
> 2693700234	echo load_core /media/fat/_Arcade/'Robocop (World revision 4).mra' > /dev/MiSTer_cmd
> #################################################################################################
> ```
> 
> Note: I had manually added the Robocop line yesterday. Also, I tried to revert my change of rootPath to the original value (using "fat"): same problem, with a path containing "fat" instead of usb0 in the conf file.


~~It looks like your MiSTer may not be all the way up-to-date. The `/tmp/CURRENTCORE`, `/tmp/FULLPATH`, etc. are features that were added within the last few months. Can you update your MiSTer when you have a moment and see if it works? Those files should hold some information that the write process depends on.~~

I remember now! You need to enable this in your MiSTer.ini: `log_file_entry`. Another candidate for the ReadMe.


Lastly: I will be going through and refactoring a lot of the variables as this gets closer to "done." Hopefully that will clean up some of the code :)

**Comment by coded-with-claws** [comment]
Hello!

I finally got time to test what you proposed!
With "log_file_entry=1" into the .ini, I no longer get errors and I finally can use the "write tag" feature to associate RFID cards with the games!!! I'm so happy! :)

About the SNES, I also have a simpler hierarchy for the fullset (whereas I previously showed you my directory for favorites), like:
```
ls -l /media/usb0/games/SNES/S-S/Super*Bomber*

-rwxr-xr-x 1 root root 1048576 Dec 24  1996 '/media/usb0/games/SNES/S-S/Super Bomber Man 2 (Japan).sfc'
```
I ran Super bomberman 2, then used the write tag, which updated the conf file with:
```
1589700154	echo load_core "/media/fat/../usb0/games/SNES/S-S/Super Bomber Man 2 (Japan).sfc.mgl" > /dev/MiSTer_cmd
```
I thought it could work because the path for this mgl file really was created. But when I scan the RFID tag, it runs the SNES core without loading the game.
Here is what I got into the mgl:
```
cat "/media/fat/../usb0/games/SNES/S-S/Super Bomber Man 2 (Japan).sfc.mgl"
<mistergamedescription><rbf>_Console/SNES</rbf><file delay="2" type="f" index="0" path="Super Bomber Man 2 (Japan).sfc.sfc"/></mistergamedescription>
```
I'll try your "find-file" branch edit when I got time again.
I'll keep you informed!

**Comment by ElRojo** [comment]
> Hello!
> 
> I finally got time to test what you proposed! With "log_file_entry=1" into the .ini, I no longer get errors and I finally can use the "write tag" feature to associate RFID cards with the games!!! I'm so happy! :)
> 
> About the SNES, I also have a simpler hierarchy for the fullset (whereas I previously showed you my directory for favorites), like:
> 
> ```
> ls -l /media/usb0/games/SNES/S-S/Super*Bomber*
> 
> -rwxr-xr-x 1 root root 1048576 Dec 24  1996 '/media/usb0/games/SNES/S-S/Super Bomber Man 2 (Japan).sfc'
> ```
> 
> I ran Super bomberman 2, then used the write tag, which updated the conf file with:
> 
> ```
> 1589700154	echo load_core "/media/fat/../usb0/games/SNES/S-S/Super Bomber Man 2 (Japan).sfc.mgl" > /dev/MiSTer_cmd
> ```
> 
> I thought it could work because the path for this mgl file really was created. But when I scan the RFID tag, it runs the SNES core without loading the game. Here is what I got into the mgl:
> 
> ```
> cat "/media/fat/../usb0/games/SNES/S-S/Super Bomber Man 2 (Japan).sfc.mgl"
> <mistergamedescription><rbf>_Console/SNES</rbf><file delay="2" type="f" index="0" path="Super Bomber Man 2 (Japan).sfc.sfc"/></mistergamedescription>
> ```
> 
> I'll try your "find-file" branch edit when I got time again. I'll keep you informed!

wow this is actually a very surprising output. I'd bet that card would work if you remove the extra `.sfc` in the mgl file. Can you try that and let me know if it works?


Edit: Okay, wow this is crazy. `FULLPATH, CURRENTPATH, STARTPATH` all have different outputs when using a USB drive for game storage. Looks like I have a bit of work to do this weekend.

**Comment by ElRojo** [comment]
Okay, @coded-with-claws , I just pushed some changes to this branch (conf-file) that _should_ fix your issue. :) 

I know it'll work for SNES, but I'm downloading some ROMs for mega drive etc. and will test those soon.

**Comment by coded-with-claws** [comment]
New tests here!
As you proposed, I manually edited the mgl file to remove the extra ".sfc": didn't work.
So I used the new code in conf-file, clean conf file, re-associate super bomberman 2 to tag: the tag still runs only the core without the game.
I got this mgl written:
```
cat "/media/fat/../usb0/games/SNES/S-S/Super Bomber Man 2 (Japan).mgl"
<mistergamedescription><rbf>_Console/SNES</rbf><file delay="2" type="f" index="0" path="Super Bomber Man 2 (Japan).sfc"/></mistergamedescription>
```

If I edit the mgl file to add "S-S/" into the path of the sfc file, it works!
```
cat "/media/fat/../usb0/games/SNES/S-S/Super Bomber Man 2 (Japan).mgl"
<mistergamedescription><rbf>_Console/SNES</rbf><file delay="2" type="f" index="0" path="S-S/Super Bomber Man 2 (Japan).sfc"/></mistergamedescription>
```

Then, I copied rfid_write.sh from the find-file branch (I saw it takes into account the renaming of game_list.conf) to my mister.
But it wrote a buggy line into config file:
```
1589700154	echo load_core ".mgl" > /dev/MiSTer_Cmd
```

I tried to debug:
```
find /media/usb0/games/SNES/ -name "Super Bomber Man 2 (Japan).sfc.*" -print
```
returns nothing

It's because "/tmp/CURRENTPATH" gives "Super Bomber Man 2 (Japan).sfc" which contains the ".sfc" extension.
So we can't find a ".sfc.something" file.

If I remove the dot in the find, it's working (but I dunno if other cores will give the extension everytime):
```
find /media/usb0/games/SNES/ -name "Super Bomber Man 2 (Japan).sfc*" -print
/media/usb0/games/SNES/S-S/Super Bomber Man 2 (Japan).sfc
```

So I patched the find command into findIt() but the whole write tag feature still didn't work.
Then I understood: the loop on rootDirs finds that I have three directories existing:
```
/media/usb0/games
/media/usb1/games
/media/fat/games
```
The variable gamesDir gets set to the last one, `/media/fat/games`, which doesn't contains my games (only the bios files).
So I kept only this:
```
rootDirs=(
  "/media/usb0/games"
)
```
And it wrote the good conf file and mgl (same content than when I manually fixed)
```
1589700154	echo load_core "/media/usb0/games/SNES/S-S/Super Bomber Man 2 (Japan).mgl" > /dev/MiSTer_Cmd

```


```
cat "/media/usb0/games/SNES/S-S/Super Bomber Man 2 (Japan).mgl"
<mistergamedescription><rbf>_Console/SNES</rbf><file delay="2" type="f" index="0" path="S-S/Super Bomber Man 2 (Japan).sfc"/></mistergamedescription>

```

BUT when I scan the tag, it does nothing!
In "screen -r", I see that it tries to run the mgl:
```
Running: echo load_core "/media/usb0/games/SNES/S-S/Super Bomber Man 2 (Japan).mgl" > /dev/MiSTer_Cmd
```
I don't understand :-O (because it worked previously when I had manually fixed the .mgl file)


By the way, there is a typo on line 97 for SNES zip extension: missing a equal sign ;)
I pushed the fix on find-file branch.

**Comment by coded-with-claws** [comment]
OK I found out!!
There was a typo into the find-file branch, the conf file contained a redirect to /dev/MiSTer_Cmd (uppercase 'C') instead of /dev/MiSTer_cmd, which made the SNES games not launching!
Weirdly enough, it didn't stop the Arcade cores to run, that's was tricky!
I spotted it while comparing the two conf files I obtained with the 2 branches :)
I pushed a fix into find-file branch.

To sum up, find-file branch worked for me with the "findIt()" fix (removing the dot before the * wildcard, but I didn't push a commit because I don't know yet about other cores than SNES" and the rootDirs fix (I don't know yet how this could be generically fixed).

```
rootDirs=(
  "/media/usb0/games"
)


  findIt() {
    foundGame=$(find "$fullCorePath" -name "$1*" -print) #/media/fat/games/CORE/Game
  }

```

**Comment by ElRojo** [comment]
> OK I found out!!
> 
> There was a typo into the find-file branch, the conf file contained a redirect to /dev/MiSTer_Cmd (uppercase 'C') instead of /dev/MiSTer_cmd, which made the SNES games not launching!
> 
> Weirdly enough, it didn't stop the Arcade cores to run, that's was tricky!
> 
> I spotted it while comparing the two conf files I obtained with the 2 branches :)
> 
> I pushed a fix into find-file branch.
> 
> 
> 
> To sum up, find-file branch worked for me with the "findIt()" fix (removing the dot before the * wildcard, but I didn't push a commit because I don't know yet about other cores than SNES" and the rootDirs fix (I don't know yet how this could be generically fixed).
> 
> 
> 
> ```
> 
> rootDirs=(
> 
>   "/media/usb0/games"
> 
> )
> 
> 
> 
> 
> 
>   findIt() {
> 
>     foundGame=$(find "$fullCorePath" -name "$1*" -print) #/media/fat/games/CORE/Game
> 
>   }
> 
> 
> 
> ```

You're on fire! Nice find!! I have company over this weekend, but I'll try to do some testing tomorrow night, as well. 

Thanks so much for all your help 🙌🏻🙌🏻🙌🏻

**Comment by coded-with-claws** [comment]
With pleasure :)
Thank you for all your work on the RFID feature, it's so great!!

I experimented about the gamesDir so it would handle all games path:
```
# Use all game dirs
for d in ${rootDirs[@]}; do
  if [ -d "$d" ]; then
    gamesDir+=("$d")
  fi
done

[...]

# Add the corename at the end of each game dir
fullCorePathv2=("${gamesDir[@]/%/\/"$coreName"}")

[...]
# Search in all game dirs
foundGame=$(find "${fullCorePathv2[@]}" -name "$1*" -type f -print) #/media/fat/games/CORE/Game
```
It worked, but such adaptations would still be needed for all variables using gamesDir:
fullGamePath, coreFullGamesPath (really used?), processedName...

**Comment by ElRojo** [comment]
> With pleasure :) Thank you for all your work on the RFID feature, it's so great!!
> 
> I experimented about the gamesDir so it would handle all games path:
> 
> ```
> # Use all game dirs
> for d in ${rootDirs[@]}; do
>   if [ -d "$d" ]; then
>     gamesDir+=("$d")
>   fi
> done
> 
> [...]
> 
> # Add the corename at the end of each game dir
> fullCorePathv2=("${gamesDir[@]/%/\/"$coreName"}")
> 
> [...]
> # Search in all game dirs
> foundGame=$(find "${fullCorePathv2[@]}" -name "$1*" -type f -print) #/media/fat/games/CORE/Game
> ```
> 
> It worked, but such adaptations would still be needed for all variables using gamesDir: fullGamePath, coreFullGamesPath (really used?), processedName...

After a bit more testing, I am not certain the `rootDirs` array is necessary. I have removed it and changed some of the logic on the `find-file` branch. Go ahead and try it out. 

I tested it using a USB drive and a nested folder for SNES. I haven't had any issues so-far. It might be fine as-is.
If that branch works, I will likely clean up the ReadMe, merge the `find-file` branch into main, and then refactor. I am certain that I'm repeating steps and have unnecessary variables all over the place -- but for now, it works. I can always optimize later.

**Comment by coded-with-claws** [comment]
Hello!
I tested the `find-file` branch with your recent changes, it works great!! For both hierarchies I got for SNES (the "fullset" one with "S-S/..." and the favorites one with "00-favs/...").
FYI, the info in "screen -r":
```
bash-5.0# bash-5.0# kicking off
1 <- has extension
Super Bomberman 2 (U) [!].smc game in findit
/media/fat/../usb0/games/SNES/00-fav/bomberman_like full core path in findit
/media/fat/../usb0/games/SNES/00-fav/bomberman_like/Super Bomberman 2 (U) [!].smc found game after findit
/media/fat/../usb0/games/SNES/00-fav/bomberman_like/Super Bomberman 2 (U) [!].smc <- fullFoundGamePath hasExtension = 1
/media/fat/../usb0/games/SNES/00-fav/bomberman_like/Super Bomberman 2 (U) [!] <- fullFoundGamePathNoExt
```

But after then, I got a weird behavior:
After adding a card for SNES Super bomberman 2 then adding another card for The punisher (CPS1): the conf file was updated correctly, but when I scanned the cards to run the games, nothing worked. In "screen -r", no new logs appeared to say that it's trying to run games.
After rebooting the MiSTer, it worked well to run all the games.
Maybe a problem in the arduino code?
Or maybe I tried to scan a new card too early after the loading of a core of the previous card. I thinking of that because I can't open the core menu just after the core loading, it needs a little time to allow the gamepad input to open the menu).

So far, it seems you got a good version. Personally I think you can do the merge :+1:

**Comment by coded-with-claws** [comment]
Ok, I did some more tests: the problem I talked about indeed appears if I scan a new card just after the core opening for the previous card. The new game doesn't run, and I can't scan any other card.
I suspect it's simply an issue due to MiSTer internal code, and it's rather a "testing" issue than a "real life" issue. We are not expected to scan a new card just after scanning a card :)

Thanks for having taken time to support loading games on USB and with a deep folder hierarchy :pray:

**Comment by ElRojo** [comment]
> Ok, I did some more tests: the problem I talked about indeed appears if I scan a new card just after the core opening for the previous card. The new game doesn't run, and I can't scan any other card. I suspect it's simply an issue due to MiSTer internal code, and it's rather a "testing" issue than a "real life" issue. We are not expected to scan a new card just after scanning a card :)
> 
> Thanks for having taken time to support loading games on USB and with a deep folder hierarchy 🙏


Interesting. I'll play around with that new-card behavior and try to duplicate it. But Yeah! I think this is a good time to merge! I'm going to make a few more edits tomorrow. on the ReadMe and a clean up some duplicated work; but I'll probably merge this weekend. Thanks for taking the time to test this all out!! This has been really fun!

**Pull request closed without merging**
